---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://localhost:5000"
    includePaths:
    - "http://localhost:5000.*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters: {}
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
  name: "spider"
  type: "spider"
- parameters:
    context: ""
    user: ""
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 0
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "off"
    rules:
    - id: 6
      name: "Path Traversal"
      threshold: "low"
      strength: "default"
  name: "activeScan"
  type: "activeScan"

