---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://localhost:5000"
    includePaths: []
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters: {}
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
  name: "spider"
  type: "spider"
- parameters:
    context: ""
    user: ""
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 0
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "off"
    rules:
    - id: 40014
      name: "Cross Site Scripting (Persistent)"
      threshold: "medium"
      strength: "default"
    - id: 40016
      name: "Cross Site Scripting (Persistent) - Prime"
      threshold: "medium"
      strength: "default"
    - id: 40017
      name: "Cross Site Scripting (Persistent) - Spider"
      threshold: "medium"
      strength: "default"
    - id: 40012
      name: "Cross Site Scripting (Reflected)"
      threshold: "medium"
      strength: "default"
  name: "activeScan"
  type: "activeScan"

